### ISSUE TITLE
Document changes for 0.18

### ISSUE THREAD

**Issue by cschneid** [rtfeldman/elm-css#190]
When attempting to compile a CSS file that worked in 0.17, I got the following error:

```
Error: TypeError: Elm[stylesheetsModule].worker is not a function
```

The solution was in the Elm Slack chat.

Change the `main` function to use `Platform.program`, and you can remove the `view` argument.

```
main : Program Never () msg
main =
    Platform.program
        { init = ( (), files cssFiles )
        , update = \_ _ -> ( (), Cmd.none )
        , subscriptions = \_ -> Sub.none
        }
```

**Comment by Pisys** [comment]
Thx for working this out!

**Comment by carlthuringer** [comment]
It looks like the API was significantly simplified in the move to 0.18. See: [The Example](https://github.com/rtfeldman/elm-css/blob/3b84d3a8ff65967345e218b81a7545d7d0bd6f9c/examples/src/Stylesheets.elm)

**Comment by tolgap** [comment]
@cschneid this seems to have been addressed in PR #197 .

**Comment by rtfeldman** [comment]
Fixed in https://github.com/rtfeldman/elm-css/pull/197 - thanks all!
